### PR TITLE
Fixed issue when parsing httpx output. Fixes #738 #739

### LINKED ISSUE #738: Scan issue - Screenshots, http responses not working
Hi,

Screenshots, HTTP responses, and technology detection not working.
These error logs occur after the httpx tool.
image

I think the issue started when configured with the last commits that support a proxy or something regarding the last commits.
@yogeshojha 
Please help to fix that ASAP.
Thanks

### PR DESCRIPTION
**Pull request by kr0no**

### CODE REVIEW

**Review by roisec — APPROVED** [review]
I also see this as the right problem.
please merge it.

**Comment by roisec** [comment]
@kr0no ,please also fix line 903 to status_code from status-code.

**Comment by kr0no** [comment]
@roisec done. I forgot that line when i locally patched the github version, thx for noticing.

**Comment by roisec** [comment]
@kr0no , Another problem, httpx change the result json for the technology key.
They changed to tech, so you also need to change line 855,856 to tech from technologies.

**Review by yahod — APPROVED** [review]

**Pull request closed without merging**
