### PR TITLE
SSL Revamp

### PR DESCRIPTION
**Pull request by JoshuaMart**
Hi,
I made some modifications to add an installation with Traefik, this step allows to have SSL certificates via Let's Encrypt, which is cleaner I think and facilitates the installation process.

I hesitate to integrate the possibility to automatically install docker & docker-composite in the `install.sh`, just let me know.

Regards,
Jomar

### CODE REVIEW

**Comment by yogeshojha** [comment]
I am going through this, please give me some time. ❤️

**Comment by yogeshojha** [comment]
One quick question, how does the ssl certs behave while installing reNgine on VPS directly, without the custom domain name, like accessing from direct IP?

**Comment by yogeshojha** [comment]
Screenshot 2020-12-01 at 8 13 06 PM
Is this intended?

**Comment by JoshuaMart** [comment]
Hi,
I don't have this problem with the install (tested on v0.5)
Rengine

Concerning IP, indeed it requires to have a domain, maybe it is possible to do without but in some cases Traefik has no interest.

The problem is that at the moment it doesn't always work with Firefox, it's impossible to access Rengine with a self-signed certificate.

**Comment by JoshuaMart** [comment]
Hi,  
After a lot of tests I finally think that this PR does not have that place, to allow the most freedom and choice of configurations to the users, it is better not to include at all the management of SSL certificates in the repository.

This would avoid chaining layers (proxy) to get a clean configuration that would not integrate properly in a docker environment anyway.

For example, whether we add this PR or not, I have to make a lot of modifications to integrate Rengine in my environment.

I also made some tests with [PwnMachine](https://github.com/yeswehack/pwn-machine), which is difficult to include Rengine as it is.

**Pull request closed without merging**
