### PR TITLE
not exposing unecessary containers publicly

### PR DESCRIPTION
**Pull request by noraj**
postgres and the internal container shouldn't be exposed publicly, only the reverse proxy should.

### CODE REVIEW

**Review by yogeshojha — COMMENTED** [review]
Hi, I was going through this PR. Sorry for keeping this pending for so long. 

I can still see the ports being exposed. I think it is better to remove ports at all for db right?

**Comment by noraj** [comment]
> I can still see the ports being exposed. I think it is better to remove ports at all for db right?

Yes you can on 127.0.0.1:8000 but it will not be exposed on all interfaces (0.0.0.0) as by default, this is especially important on VPS.

**Review by atolac — APPROVED** [review]

**Comment by AnonymousWP** [comment]
What do we do with this PR?

**Comment by psyray** [comment]
We could restrict port to 127.0.0.1 only

**Comment by AnonymousWP** [comment]
> We could restrict port to 127.0.0.1 only

What do you mean? That's happening with this PR.

**Comment by psyray** [comment]
> > We could restrict port to 127.0.0.1 only
> 
> What do you mean? That's happening with this PR.

I mean, go merging this one

**Comment by AnonymousWP** [comment]
This needs 2 more approvals before I can merge though. :)

**Review by psyray — APPROVED** [review]

**Review by AnonymousWP — APPROVED** [review]
Approved. Please wait with merging.

**Comment by AnonymousWP** [comment]
What about https://github.com/yogeshojha/rengine/blob/master/docker-compose.dev.yml btw? Doesn't it need to be applied there?

**Review by yogeshojha — APPROVED** [review]

**Pull request merged**
