### PR TITLE
fix(external_tools): incorrect "update available" strings

### PR DESCRIPTION
**Pull request by AnonymousWP**
# Fixes

- **Incorrect update string theHarvester:** before, it somehow detected version v5, which doesn't even exist. However, the current version ('v3') isn't detected properly and I'm not sure how to solve it. It doesn't even seem to update the tool, but that could also be a detection issue as I said.

**Before:** 

image

image

**After:**

image

image

# Changes

- Incorrect version number of reNgine at login page

### CODE REVIEW

**Comment by psyray** [comment]
Hi
As a workaround
Try to set this value in the database, table `scanEngine_installedexternaltool`
`cd /usr/src/github/theHarvester/theHarvester/lib/;python3 -c 'from version import version; print(version())'`
but you need to grow the `version_lookup_command` to 110 chars
Don't know if this changes will persist during an upgrade

**Comment by psyray** [comment]
OK find the way to persist, because after each restart of celery, db is reinitialized from fixtures
Here comes the update fixtures (with more things  like ffuf and gospider logo, github location of missing ones and github clone value set to true for those ones)
```yaml
- model: scanEngine.installedexternaltool
  pk: 1
  fields:
    logo_url: https://raw.githubusercontent.com/projectdiscovery/subfinder/master/static/subfinder-logo.png
    name: subfinder
    description: Subfinder is a subdomain discovery tool that discovers valid subdomains
      for websites by using passive online sources.
    github_url: https://github.com/projectdiscovery/subfinder
    license_url: https://github.com/projectdiscovery/subfinder/blob/master/LICENSE.md
    version_lookup_command: subfinder -version
    update_command: go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    install_command: go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: true
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 2
  fields:
    logo_url: https://raw.githubusercontent.com/projectdiscovery/nuclei/master/static/nuclei-logo.png
    name: Nuclei
    description: Nuclei is used to send requests across targets based on a template
      leading to zero false positives and providing fast scanning on large number
      of hosts. Nuclei offers scanning for a variety of protocols including TCP, DNS,
      HTTP, File, etc. With powerful and flexible templating, all kinds of security
      checks can be modelled with Nuclei.
    github_url: https://github.com/projectdiscovery/nuclei
    license_url: https://github.com/projectdiscovery/nuclei/blob/master/LICENSE.md
    version_lookup_command: nuclei -version
    update_command: nuclei -update
    install_command: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
    version_match_regex: (\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 3
  fields:
    logo_url: https://raw.githubusercontent.com/projectdiscovery/httpx/master/static/httpx-logo.png
    name: httpx
    description: httpx is a fast and multi-purpose HTTP toolkit allow to run multiple
      probers using retryablehttp library, it is designed to maintain the result reliability
      with increased threads.
    github_url: https://github.com/projectdiscovery/httpx
    license_url: https://github.com/projectdiscovery/httpx/blob/master/LICENSE.md
    version_lookup_command: httpx -version
    update_command: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
    install_command: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 4
  fields:
    logo_url: https://raw.githubusercontent.com/projectdiscovery/naabu/master/static/naabu-logo.png
    name: naabu
    description: Naabu is a port scanning tool written in Go that allows you to enumerate
      valid ports for hosts in a fast and reliable manner. It is a really simple tool
      that does fast SYN/CONNECT scans on the host/list of hosts and lists all ports
      that return a reply.
    github_url: https://github.com/projectdiscovery/naabu
    license_url: null
    version_lookup_command: naabu -version
    update_command: go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
    install_command: go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 5
  fields:
    logo_url: https://raw.githubusercontent.com/osmedeus/assets/main/logo-transparent.png
    name: gospider
    description: Fast web spider written in Go
    github_url: https://github.com/jaeles-project/gospider
    license_url: https://github.com/jaeles-project/gospider/blob/master/LICENSE
    version_lookup_command: gospider --version
    update_command: go install -v github.com/jaeles-project/gospider@latest
    install_command: go install -v github.com/jaeles-project/gospider@latest
    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 6
  fields:
    logo_url: https://raw.githubusercontent.com/owasp-amass/amass/master/images/amass_logo.png
    name: amass
    description: The OWASP Amass Project performs network mapping of attack surfaces
      and external asset discovery using open source information gathering and active
      reconnaissance techniques.
    github_url: https://github.com/owasp-amass/amass
    license_url: https://github.com/owasp-amass/amass/blob/master/LICENSE
    version_lookup_command: amass -version
    update_command: go install -v github.com/owasp-amass/amass/v3/...@latest
    install_command: go install -v github.com/owasp-amass/amass/v3/...@latest
    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: true
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 7
  fields:
    logo_url: https://github.com/ffuf/ffuf/raw/master/_img/ffuf_run_logo_600.png
    name: ffuf
    description: A fast web fuzzer written in Go.
    github_url: https://github.com/ffuf/ffuf
    license_url: https://github.com/ffuf/ffuf/blob/master/LICENSE
    version_lookup_command: ffuf -V
    update_command: go install -v github.com/ffuf/ffuf@latest
    install_command: ''
    version_match_regex: (\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 8
  fields:
    logo_url: null
    name: assetfinder
    description: Find domains and subdomains potentially related to a given domain.
    github_url: https://github.com/tomnomnom/assetfinder
    license_url: https://github.com/tomnomnom/assetfinder/blob/master/LICENSE
    version_lookup_command: null
    update_command: go install -v github.com/tomnomnom/assetfinder@latest
    install_command: go install -v github.com/tomnomnom/assetfinder@latest
    version_match_regex: null
    is_default: true
    is_subdomain_gathering: true
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 9
  fields:
    logo_url: null
    name: sublist3r
    description: Sublist3r is a python tool designed to enumerate subdomains of websites
      using OSINT. It helps penetration testers and bug hunters collect and gather
      subdomains for the domain they are targeting. Sublist3r enumerates subdomains
      using many search engines such as Google, Yahoo, Bing, Baidu and Ask. Sublist3r
      also enumerates subdomains using Netcraft, Virustotal, ThreatCrowd, DNSdumpster,
      and ReverseDNS.
    github_url: https://github.com/aboul3la/Sublist3r
    license_url: https://github.com/aboul3la/Sublist3r/blob/master/LICENSE
    version_lookup_command: null
    update_command: git pull
    install_command: git clone https://github.com/aboul3la/Sublist3r.git
    version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
    is_default: true
    is_subdomain_gathering: true
    is_github_cloned: true
    github_clone_path: /usr/src/github/Sublist3r
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 10
  fields:
    logo_url: null
    name: hakrawler
    description: Fast golang web crawler for gathering URLs and JavaSript file locations.
      This is basically a simple implementation of the awesome Gocolly library.
    github_url: https://github.com/hakluke/hakrawler
    license_url: https://github.com/hakluke/hakrawler/blob/master/LICENSE
    version_lookup_command: null
    update_command: go install -v github.com/hakluke/hakrawler@latest
    install_command: go install -v github.com/hakluke/hakrawler@latest
    version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: false
    github_clone_path: null
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 11
  fields:
    logo_url: null
    name: gauplus
    description: Get all URLs
    github_url: https://github.com/bp0lr/gauplus
    license_url: https://github.com/bp0lr/gauplus/blob/main/LICENSE
    version_lookup_command: null
    update_command: go install -v -v github.com/bp0lr/gauplus@latest
    install_command: go install -v -v github.com/bp0lr/gauplus@latest
    version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: true
    github_clone_path: /usr/src/github/gauplus
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 12
  fields:
    logo_url: null
    name: OneForAll
    description: A powerful subdomain integration tool.
    github_url: https://github.com/shmilylty/OneForAll
    license_url: https://github.com/shmilylty/OneForAll/blob/master/LICENSE
    version_lookup_command: null
    update_command: git pull
    install_command: git clone https://github.com/shmilylty/OneForAll
    version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
    is_default: true
    is_subdomain_gathering: true
    is_github_cloned: true
    github_clone_path: /usr/src/github/OneForAll
    subdomain_gathering_command: null
- model: scanEngine.installedexternaltool
  pk: 13
  fields:
    logo_url: https://raw.githubusercontent.com/laramies/theHarvester/master/theHarvester-logo.png
    name: theHarvester
    description: theHarvester is a very simple to use, yet powerful and effective
      tool designed to be used in the early stages of a penetration test or red team
      engagement. Use it for open source intelligence (OSINT) gathering to help determine
      a company's external threat landscape on the internet. The tool gathers emails,
      names, subdomains, IPs and URLs using multiple public data sources.
    github_url: https://github.com/laramies/theHarvester
    license_url: null
    version_lookup_command: cd /usr/src/github/theHarvester/theHarvester/lib/;python3 -c 'from version import version;print(version())'
    update_command: git pull
    install_command: git clone https://github.com/laramies/theHarvester
    version_match_regex: (\d+\.)?(\d+\.)?(\*|\d+)
    is_default: true
    is_subdomain_gathering: false
    is_github_cloned: true
    github_clone_path: /usr/src/github/theHarvester
    subdomain_gathering_command: null
```

**Comment by psyray** [comment]
Ok found the problem, output line from naabu & httpx is bytes utf-8 encoded
So the solution is :
Use `str(line, encoding='utf-8'))` instead of `str(line)`
Here https://github.com/yogeshojha/rengine/blob/d17c0acb7ddde9e0f11021226bcd58a1ebafcbd9/web/api/views.py#L802

**Comment by psyray** [comment]
To display the correct version for naabu and httpx you must correct the `str(line)` part AND the YAML regex.
Here's the path for the YAML
```patch
--- <sans nom>
+++ <sans nom>
@@ -31,7 +31,7 @@
     version_lookup_command: nuclei -version
     update_command: nuclei -update
     install_command: go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
-    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
+    version_match_regex: (\d+\.)?(\d+\.)?(\*|\d+)
     is_default: true
     is_subdomain_gathering: false
     is_github_cloned: false
@@ -47,7 +47,7 @@
       with increased threads.
     github_url: https://github.com/projectdiscovery/httpx
     license_url: https://github.com/projectdiscovery/httpx/blob/master/LICENSE.md
-    version_lookup_command: /go/bin/httpx -version
+    version_lookup_command: httpx -version
     update_command: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
     install_command: go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
     version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
@@ -70,7 +70,7 @@
     version_lookup_command: naabu -version
     update_command: go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
     install_command: go install -v github.com/projectdiscovery/naabu/v2/cmd/naabu@latest
-    version_match_regex: ' (\d+\.)?(\d+\.)?(\*|\d+)'
+    version_match_regex: v(\d+\.)?(\d+\.)?(\*|\d+)
     is_default: true
     is_subdomain_gathering: false
     is_github_cloned: false
@@ -79,7 +79,7 @@
 - model: scanEngine.installedexternaltool
   pk: 5
   fields:
-    logo_url: https://raw.githubusercontent.com/osmedeus/assets/main/logo-transparent.png
+    logo_url: null
     name: gospider
     description: Fast web spider written in Go
     github_url: https://github.com/jaeles-project/gospider
@@ -115,7 +115,7 @@
 - model: scanEngine.installedexternaltool
   pk: 7
   fields:
-    logo_url: https://github.com/ffuf/ffuf/raw/master/_img/ffuf_run_logo_600.png
+    logo_url: null
     name: ffuf
     description: A fast web fuzzer written in Go.
     github_url: https://github.com/ffuf/ffuf
@@ -165,8 +165,8 @@
     version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
     is_default: true
     is_subdomain_gathering: true
-    is_github_cloned: true
-    github_clone_path: /usr/src/github/Sublist3r
+    is_github_cloned: false
+    github_clone_path: null
     subdomain_gathering_command: null
 - model: scanEngine.installedexternaltool
   pk: 10
@@ -200,8 +200,8 @@
     version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
     is_default: true
     is_subdomain_gathering: false
-    is_github_cloned: true
-    github_clone_path: /usr/src/github/gauplus
+    is_github_cloned: false
+    github_clone_path: null
     subdomain_gathering_command: null
 - model: scanEngine.installedexternaltool
   pk: 12
@@ -217,8 +217,8 @@
     version_match_regex: '[vV]*(\d+\.)?(\d+\.)?(\*|\d+)'
     is_default: true
     is_subdomain_gathering: true
-    is_github_cloned: true
-    github_clone_path: /usr/src/github/OneForAll
+    is_github_cloned: false
+    github_clone_path: null
     subdomain_gathering_command: null
 - model: scanEngine.installedexternaltool
   pk: 13
@@ -232,7 +232,7 @@
       names, subdomains, IPs and URLs using multiple public data sources.
     github_url: https://github.com/laramies/theHarvester
     license_url: null
-    version_lookup_command: cd /usr/src/github/theHarvester/theHarvester/lib/;python3 -c 'from version import version;print(version())'
+    version_lookup_command: python3 /usr/src/github/theHarvester/theHarvester.py
     update_command: git pull
     install_command: git clone https://github.com/laramies/theHarvester
     version_match_regex: (\d+\.)?(\d+\.)?(\*|\d+)
```
However for the Naabu part I have a strange behaviour, maybe you could help.
If you pay attention to my screen, theere is a space between the`v` and `2.1.6`, without space the version is not recognized correctly.
But with the space, version is correctly recognized, but when you try to update the comparison fail because of the space 
Maybe you have an idea ?

For the PR do as you want.
I could do the PR if you want.

**Comment by AnonymousWP** [comment]
Have you tested all of this? I committed the `str` fix, please review it. I can't fix the theHarvester issue I'm afraid. The YAML regexes seem kinda... odd. Did you test it and can you confirm this (sometimes weird) workaround fixes it?

**Comment by psyray** [comment]
> Have you tested all of this? I committed the `str` fix, please review it. 
Yes all the modification are tested an working on my install.
The only thing that works weird is naabu, I didn't find the right regex, there is a space between the `v` and the version number.
That cause the comparison to fail when you choose to update.
But it's the right version displayed.

>I can't fix the theHarvester issue I'm afraid. The YAML regexes seem kinda... odd. Did you test it and can you confirm this (sometimes weird) workaround fixes it?

Yes it is tested and working on my install
But I know it's complicated because you must enlarge the field in the database.

**Comment by scristofaro** [comment]
Why don't use v\d.* as regex for naabu?

**Comment by psyray** [comment]
> Why don't use v\d.* as regex for naabu?

Because Naabu doesn't return the `v`
```
naabu -version

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

		projectdiscovery.io

[INF] Current Version: 2.1.7
```
Feel free to improve my bad regex :wink:

**Comment by AnonymousWP** [comment]
I pushed some new commits, but I think some of your `external_tools.yaml` are incorrect: I believe `is_github_cloned` should only be `true` if `update_command` is done by a `git pull` and the `install_command` is `git clone <repo_url>`. Now you've changed that are installed by Go to `true` as well.

@psyray Can you let me know what you think of it?

**Comment by AnonymousWP** [comment]
I don't think it has the desired result, lol. A lot still can't recognise the version, and if it can, the version number remains the same after updating. It's very annoying.

image
image

**Comment by psyray** [comment]
We could close this one, I have reworked this part on PR #995

**Pull request closed without merging**
