### PR TITLE
Add amass active to search subdomain

### PR DESCRIPTION
**Pull request by Serizao**
Hello this tools is wonderful :) , i create pull request to add Amass "active" sub domain discover. Amass work ver well with config file for specify API key. In the future release i think that's will very nice to include possibility to add api key or config file to Amass

### CODE REVIEW

**Comment by yogeshojha** [comment]
Hi @Serizao, Thank you so much for the PR. Much appreciated.

There's a little more than editing the script. There was another feature request to upload the configuration file, which I am going to work on. 

Your contributions are much appreciated, and I will be further enhancing this. 
In the meanwhile, I will keep this PR open.

Thank you so much once again.

**Comment by Serizao** [comment]
hi, I'am working on nuclei intergration what we must do to integrate tools proprely ? If i understand your code *.sh code make only loop and if tools name are recognize also the tools are launch isn't it ?

**Comment by yogeshojha** [comment]
Hi @Serizao, Can you please tick the checkbox that says allow edit from maintainers? I am not able to puch the changes to this PR. It should be there somewhere bottom right widget.

**Comment by yogeshojha** [comment]
This!
Screenshot 2020-07-24 at 11 40 53 PM

Please inform me once you have done so

**Comment by Serizao** [comment]
Hello ,

That's already checked. Can you try again i have uncheck and checked the box

**Pull request closed without merging**
