### PR TITLE
Add django debug toolbar

### PR DESCRIPTION
**Pull request by psyray**
For easier debug, I'm adding the [Django Debug Toolbar.](https://pypi.org/project/django-debug-toolbar/)

image

image

Now we can profile app for bottlenecks.

SQL queries are heavy on the db and we need this to correctly debug and speed up UI on huge projects
image

The most impacted part is Vulnerability Tab, more than 500 queries for only 7 lines 😵‍💫 
image

Django Debug Toolbar is automatically activated while setting the `DEBUG` env var to **1** in `web/entrypoint.sh`
Adding `export DEBUG=1` and do a `docker-compose restart` and you're up to debug.

It could also help users to submit quality issues

Complementary with #994

### CODE REVIEW

**Review by AnonymousWP — DISMISSED** [review]
Approved. Please wait with merging.

**Review by AnonymousWP — APPROVED** [review]

**Comment by psyray** [comment]
@AnonymousWP Could you test this one also ?
It works for me, I'll have to add the module in the celery-beat container because it complains of module missing at container launh

**Comment by AnonymousWP** [comment]
Push to a branch on our repo, not your fork. That way, I can easily test it without having to clone your fork.

**Comment by psyray** [comment]
> Push to a branch on our repo, not your fork. That way, I can easily test it without having to clone your fork.

Done
https://github.com/yogeshojha/rengine/tree/add-django-debug-toolbar

**Comment by AnonymousWP** [comment]
Is it supposed to be like this? Looks like a rendering issue, and it also occurs at the dashboard page. 

image

It should work though:

image

**Comment by psyray** [comment]
> Is it supposed to be like this? Looks like a rendering issue, and it also occurs at the dashboard page.
> 
> 
> It should work though:
> 

Seems you miss the CSS, should be like this
image

What's the status of the CSS load in the web console of your browser ?
image

**Comment by AnonymousWP** [comment]
Lol, not sure what happened, but it works now.

image

**Comment by psyray** [comment]
I will close this one in favor of another PR more complete with docker compose.

**Comment by psyray** [comment]
Done in #1196

**Pull request closed without merging**
