### PR TITLE
Convert user input to lowercase

### PR DESCRIPTION
**Pull request by jxdv**
Convert user input in `update.sh` & `install.sh` to lowercase, so the script(s) won't complain about Y / N.

### CODE REVIEW

**Review by AnonymousWP — APPROVED** [review]
Maybe this can be applied to different parts in the `uninstall.sh` and `update.sh` as well.

**Comment by jxdv** [comment]
> Maybe this can be applied to different parts in the `uninstall.sh` and `update.sh` as well.

I presume you meant `uninstall.sh` and `install.sh` since I've already updated `update.sh`, and yes looks like It is applicable there also. I'll update those scripts.

**Comment by jxdv** [comment]
Converted the user input to lowercase in `install.sh`. IMO `uninstall.sh` doesn't need a change.

**Review by AnonymousWP — APPROVED** [review]

**Review by psyray — APPROVED** [review]

**Comment by yogeshojha** [comment]
@jxdv please resolve the conflict

**Comment by jxdv** [comment]
> @jxdv please resolve the conflict

Done.

**Pull request merged**
