### PR TITLE
Added CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Aju100**
The goal of this PR is to make a contributing.md file

### CODE REVIEW

**Comment by yogeshojha** [comment]
Looks like you haven't pulled the latest changes. 
There is already CONTRIBUTING.md 
https://github.com/yogeshojha/rengine/blob/master/CONTRIBUTING.md

Please pull the latest changes by following the guide here
https://github.com/yogeshojha/rengine/blob/master/CONTRIBUTING.md#first-time-contributors

**Comment by Aju100** [comment]
Thank u I will fix that issue.

**Comment by yogeshojha** [comment]
I will merge this to master asap. Thanks again.

**Comment by Aju100** [comment]
@yogeshojha  thank u I hope I will be contributing more and be active in an awesome opensource project.

**Pull request merged**
