### PR TITLE
Add proxy + HTTPS

### PR DESCRIPTION
**Pull request by Creased**
That should help solving #116.

I've also added a Makefile that will help users to setup their instance (based on [this](https://github.com/sherifabdlnaby/elastdocker/)):

image

**This PR should be tested before merging! IMHO, it's a good time to consider refactoring (e.g., moving secrets, config, grouping folders, etc.)**

### CODE REVIEW

**Comment by Creased** [comment]
The [dotenv](https://github.com/Creased/rengine/blob/83836a0677afb465975450ce571aced6ba72d0a2/.env#L6-L15) file should be updated when setting up reNgine, for example:

```shell
AUTHORITY_NAME=reNgine
AUTHORITY_PASSWORD=nSrmNkwT
COMPANY=reNgine
DOMAIN_NAME=recon.example.com
COUNTRY_CODE=US
STATE=Georgia
CITY=Atlanta
```

Then use the `make cert` command to generate the certificate (inside the `secrets/certs` folder).

**Comment by yogeshojha** [comment]
Again another awesome PR from @Creased .

I am testing this and will merge once everything is okay.

I liked the make file though! 👍

**Comment by yogeshojha** [comment]
Can you also please look into this? https://www.jomar.fr/posts/2020/07/en-install-rengine-with-nginx-and-ssl-auto-renew/

**Comment by yogeshojha** [comment]
🚀  This is very much appreciated. makefile will make the setup process much easier. Can you please create the make configuration for username creation as well?

`make username`

This will make setup so much easier. 

The only bug I see is while serving the static file, not sure if nginx is causing the problem or Django. I will look into this.
Screenshot 2020-07-26 at 12 02 20 PM

**Comment by yogeshojha** [comment]
Hi, @Creased Shall we merge this? Looks good on my end. Everything seems to be working

**Comment by Creased** [comment]
LGTM too

**Pull request merged**
