### PR TITLE
Add llama2 llm

### LINKED ISSUE #1035: feat: GPT4All, Open-source large language models that run locally on your CPU and nearly any GPU
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Hi.

Can you add support for GPT4All?

It is great for local testing (3GB - 8GB) in any corporation that don't want to send data to internet.

"GPT4All is an ecosystem to run powerful and customized large language models that work locally on consumer grade CPUs and any GPU. Note that your CPU needs to support [AVX or AVX2 instructions]"

https://gpt4all.io/
https://github.com/nomic-ai/gpt4all

### Alternative solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ErdemOzgen**
* Added ollama with docker container
* GPTVulnerabilityReportGenerator : Retrieves an OpenAI API key and sets the model to 'gpt-3.5-turbo'. If the API key is not available, it initializes an Ollama instance for local use.
*  GPTAttackSuggestionGenerator: Similar to the GPTVulnerabilityReportGenerator, it retrieves an OpenAI API key and sets the model to 'gpt-3.5-turbo', or initializes an Ollama instance if the API key is not available.
* Changed makefile make up and make down sections.
* After docker container up it will run command to pull llama2-uncensored llm model and serve model.

This PR fixes #1035.

### CODE REVIEW

**Comment by ErdemOzgen** [comment]
Based on my understanding, the two failed GitHub Actions are facing distinct issues. The problem does not pertain to a Pull Request (PR). The issue with pulling the Docker image is due to an **Error: Username and password required**. Meanwhile, the Auto Comment action is encountering a different problem, which could potentially be resolved by ensuring that the GitHub token being used has the appropriate permissions.

**Comment by ErdemOzgen** [comment]
> > Based on my understanding, the two failed GitHub Actions are facing distinct issues. The problem does not pertain to a Pull Request (PR). The issue with pulling the Docker image is due to an **Error: Username and password required**. Meanwhile, the Auto Comment action is encountering a different problem, which could potentially be resolved by ensuring that the GitHub token being used has the appropriate permissions.
> 
> Would you be able to fix this by a new PR? I understand some can't be fixed due to insufficient permissions, though.

I will do my best.

**Comment by psyray** [comment]
This need to be tested, @yogeshojha You could test it ?

**Comment by yogeshojha** [comment]
Hi @ErdemOzgen,

Thank you for the excellent work.

I am closing this as I have already merged your changes through this MR
https://github.com/yogeshojha/rengine/pull/1259

Thanks

**Pull request closed without merging**
