### PR TITLE
Add Lark to notifications.

### PR DESCRIPTION
**Pull request by iuime**
Add Lark to notifications.

### CODE REVIEW

**Comment by AnonymousWP** [comment]
Can you please write a more detailed PR description? What's lark? What's the benefit?

**Comment by iuime** [comment]
> Can you please write a more detailed PR description? What's lark? What's the benefit?

Lark is developed by ByteDance and is an application similar to an instant messaging tool. It is currently widely used in China and Asian countries. Since I've noticed that others share similar needs and would like to use Lark for notifications, I suggest merging this branch. Thank you.

**Comment by AnonymousWP** [comment]
> > Can you please write a more detailed PR description? What's lark? What's the benefit?
> 
> Lark is developed by ByteDance(TikTok's parent company) and is an application similar to an instant messaging tool(Slack). It is currently widely used in China and Asian countries. Since I've noticed that others share similar needs and would like to use Lark for notifications, I suggest merging this branch. Thank you.
> 
> Lark site:https://www.larksuite.com/en_us

So this PR brings support for sending notifications/messages to Lark?

**Comment by psyray** [comment]
@iuime Everything has been tested and working on latest master branch ?

**Comment by iuime** [comment]
> > > Can you please write a more detailed PR description? What's lark? What's the benefit?
> > 
> > 
> > Lark is developed by ByteDance(TikTok's parent company) and is an application similar to an instant messaging tool(Slack). It is currently widely used in China and Asian countries. Since I've noticed that others share similar needs and would like to use Lark for notifications, I suggest merging this branch. Thank you.
> > Lark site:https://www.larksuite.com/en_us
> 
> So this PR brings support for sending notifications/messages to Lark?

Yes, sending notifications/messages to Lark.

**Comment by iuime** [comment]
> @iuime Everything has been tested and working on latest master branch ?

Yes, everything has been tested and is working on the latest master branch.

**Review by psyray — APPROVED** [review]

**Review by yogeshojha — APPROVED** [review]

**Comment by yogeshojha** [comment]
Thank you for your PR. 

Very good addition.

**Pull request merged**
