### PR TITLE
Upgrade Django to 3.2.23

### PR DESCRIPTION
**Pull request by psyray**
Related to Dependabot #916

### CODE REVIEW

**Comment by yogeshojha** [comment]
Let's not do this for now. Because changed dependencies will require a substansial effort to test out if everything works fine.

And why are we downgrading django?

**Comment by psyray** [comment]
> Let's not do this for now. Because changed dependencies will require a substansial effort to test out if everything works fine.

I'm currently testing ;)

> And why are we downgrading django?

Downgrading ? 3.2.23 is higher no ?

**Comment by psyray** [comment]
Maybe we could keep open this PR, I will log my testing result.
At present time, no problem.

**Comment by yogeshojha** [comment]
I am super confused haha :D 

what we have now is django 3.2.4, and you sent pr for 3.2.23

am I mistaken or? :laughing:

**Comment by AnonymousWP** [comment]
In my opinion we should upgrade Django too, as long as it's thoroughly tested. Because these dependencies can obviously also contain security vulnerabilities.

> And why are we downgrading django?

I think you are confused, and I can understand why, but: you should read the .4 as .04 instead. 24 is obviously a higher number than just 4. In this case, 4 doesn't indicate 40, but 04 I assume.

**Comment by psyray** [comment]
I'm using 3.2.23 until 2 weeks, nothing to say.
I think this one could be merged

**Review by yogeshojha — APPROVED** [review]

**Pull request merged**
