### PR TITLE
Enhance subdomains & vulnerabilities list ergonomy

### PR DESCRIPTION
**Pull request by psyray**
For a better ergonomy and not to have to scroll while working with huge list of subdomains, i've added :

- Top actions buttons on bottom
- Bottom count and pagination list on top

It's useful for me when i'm working on huge scope, maybe it could be useful for others

- Targets part

image
image

image
image

- Scans part

image
image

image
image

### CODE REVIEW

**Comment by psyray** [comment]
I've pushed some more enhancements

- Optimize pagination layout for tablet view

image

- Optimize pagination layout for mobile view (actions buttons reduce to icons only)

image
image

- Scan engine are now ordered by name in the subscan popup and target start scan page
It's more easy to choose the right engine when you create a lot, you can organize them by prefixing the type of scan

image

image

- Favicon has been added (need `docker-compose restart`)

image

**Comment by AnonymousWP** [comment]
Very nice work!

**Comment by psyray** [comment]
> Very nice work! Merging your changes into my fork.

Thanks, it's little thing here and there, but it makes gain a lot of time on huge scope
Another one to solve, really annoying, it's the automatic scroll to top when popup is opened.

**Comment by psyray** [comment]
I've added the responsive part for all the tables.

- Tablet view

image

- Phone view

image

image

Enjoy :wink:

**Comment by AnonymousWP** [comment]
Very neat work again, I'll merge it into my fork.

**Comment by psyray** [comment]
@AnonymousWP 
I've reset the datatable version to v1.10.16/bs4 because of the search param no taken in to account anymore.
Reset makes search works again
Didn't try to investigate the root cause, always on my mindset "no huge changes due to v2 coming soon"

**Comment by psyray** [comment]
After further investigation, it seems to be the responsive plugins that create this problem.
Don't know why, maybe the way that rengine launch search on columns.
I'll disable the responsive part because of this, search is more important than responsive UI.
I will investigate more later

**Comment by yogeshojha** [comment]
Excellent work. I am merging this into 2.0!

**Review by yogeshojha — APPROVED** [review]

**Comment by yogeshojha** [comment]
Just tested this out right before release 2.0, and I must say, this is an excellent UI addition. 

Thank you!

**Comment by psyray** [comment]
@yogeshojha is it possible for you to debug the search not working while activating the data table responsive plugin ?
If the plugin is activated, the search parameter is empty.

**Pull request merged**
