### PR TITLE
fix: ffuf ANSI code processing preventing task to finish

### LINKED ISSUE #1006: Version 2, "Directories & files fuzz - In progress" Never stop
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

"Directories & files fuzz" scan never end

### Expected Behavior

"Directories & files fuzz"

### Steps To Reproduce

Start any scan

### Environment

```markdown
- reNgine: 2
- OS: Kali
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ocervell**
Should
- [ ] fix #1006 

Needs to be tested for potential impact on other tasks (e.g: dalfox)

### CODE REVIEW

**Comment by yogeshojha** [comment]
I think its better to wait for 2.0.2 release until we test this out.

Excellent work @ocervell, will test this out tomorow.

**Comment by AnonymousWP** [comment]
> I think its better to wait for 2.0.2 release until we test this out.
> 
> Excellent work @ocervell, will test this out tomorow.

It's a pretty severe bug though, and as this PR will fix it, I think it can be safely merged. From what I'm understanding, Psyray is testing this right now.

**Comment by yogeshojha** [comment]
Lets hope so! 

Anyways @ocervell would be the best person to fix this, since he had worked on the rework of celery tasks and I think he is aware of the ffuf issue. 

I initially thought it had something to do with celery, if this PR fixes, well and good for all of us.

**Comment by psyray** [comment]
@ocervell 
Currently testing.
FFUF does not hangs but it restarts again and again
I'll let it go to see if it stops

**Comment by psyray** [comment]
Same problem, i've tested on on of my website.
In nginx log access, request stopped at the end of the wordlits
But on the server FFUF task is always running, and no SUCCESS added to log
image

**Comment by psyray** [comment]
OK found the bug.
In the Tree capture, I saw that celery was launched in `--loglevel=info`, so I've modified this in `--loglevel=info`
And BAM !
image

```
rengine-celery-1       | Traceback (most recent call last):
rengine-celery-1       |   File "/usr/src/app/reNgine/celery_custom_task.py", line 129, in __call__
rengine-celery-1       |     self.result = self.run(*args, **kwargs)
rengine-celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 1682, in dir_file_fuzz
rengine-celery-1       |     endpoint, created = save_endpoint(url, crawl=False, ctx=ctx)
rengine-celery-1       |   File "/usr/src/app/reNgine/tasks.py", line 4518, in save_endpoint
rengine-celery-1       |     endpoint, created = EndPoint.objects.get_or_create(
rengine-celery-1       |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/manager.py", line 85, in manager_method
rengine-celery-1       |     return getattr(self.get_queryset(), name)(*args, **kwargs)
rengine-celery-1       |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 581, in get_or_create
rengine-celery-1       |     return self.get(**kwargs), False
rengine-celery-1       |   File "/usr/local/lib/python3.10/dist-packages/django/db/models/query.py", line 439, in get
rengine-celery-1       |     raise self.model.MultipleObjectsReturned(
rengine-celery-1       | startScan.models.EndPoint.MultipleObjectsReturned: get() returned more than one EndPoint -- it returned 2!
```

**Comment by yogeshojha** [comment]
@psyray for me this solution works! At the same time, I believe our ffuf command is also wrong, I am checking the command once again, but ffuf starts and stops without any issues.

**Comment by yogeshojha** [comment]
Yes one of the issues is that `-e` extensions is expecting extensions to begin with `.`, example .php,.html rather than php,html

**Comment by yogeshojha** [comment]
Fuzz works fine to what I see as of now.

image

**Comment by AnonymousWP** [comment]
Also check the security alerts and its potential risks. Take action on them (e.g. dismissing if false positive).

**Comment by psyray** [comment]
> Fuzz works fine to what I see as of now.
> 
> image

@yogeshojha 
Check #1063 
Bug is dependent to duplicate field in db, so it would not come in all case

**Comment by psyray** [comment]
@ocervell Do you think we should merge this modification ?
It's implemented in my dev branch, but I don't know if it really resolve this bug because the problem was more a get_or_create crash on duplicate records than an ANSI problem

What was the use case that cause problem for you that need this modification ?

**Comment by AnonymousWP** [comment]
And please, take a look to the security advisories as I pointed out earlier.

**Comment by ocervell** [comment]
I am doubting that https://github.com/yogeshojha/rengine/pull/1063 is related only to ffuf, seems like an extra issue that could be triggered by any duplicate endpoint added to the db; for me this PR resolves the problem with ffuf not completing properly.

**Comment by yogeshojha** [comment]
I agree with @ocervell 

duplicate endpoint is coming from elsewhere. The function where we save endpoint has get_or_create, that should have never written duplicate endpoints. It is either coming from http crawler or manual entry.

**Comment by psyray** [comment]
> I agree with @ocervell
> 
> duplicate endpoint is coming from elsewhere. The function where we save endpoint has get_or_create, that should have never written duplicate endpoints. It is either coming from http crawler or manual entry.

Duplicate endpoint seems to come from the missing target_domain_id and PR has been merged.
https://github.com/yogeshojha/rengine/pull/1069

Now duplicate endpoint task should better do his job.

Maybe there's another source of duplicate.

So we need to test with a clean db and launch multiples scans, then check the db with this query
```sql
SELECT http_url, COUNT(http_url) as url_count, is_default FROM public."startScan_endpoint"
group by http_url, is_default
having COUNT(http_url) > 1
order by url_count desc
```
Or this python code
```python
>>> from django.db.models import Count
>>> EndPoint.objects.values('http_url').annotate(Count('http_url')).order_by().filter(http_url__count__gt=1)
<QuerySet [{'http_url': 'http://testphp.vulnweb.com', 'http_url__count': 2}]>
```

**Review by psyray — APPROVED** [review]

**Review by yogeshojha — APPROVED** [review]
Approved

**Pull request merged**
